dubbo:
  application:
    name: boot-hello-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: -1
  interface: test1
server:
  port: 7077