server:
  port: 7071
spring:
  application:
    name: first-dubbo-consumer
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  application:
    name: first-dubbo-consumer
  protocol: zookeeper
    name: dubbo
    port: 20880
  reference:
    check: false